package agenda.Ventanas;

import MySQL.MySQLDaoManager;
import agenda.dao.ContactoDAO;
import agenda.dao.DAOManager;
import agenda.modelos.Contacto;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

public class VentanaContacto extends javax.swing.JFrame {

    DefaultTableModel modelo;

    Contacto contacto = new Contacto();

    DAOManager manager;
    
    //creo un constructor que le pueda pasar el manager al Frame
    
    public VentanaContacto(DAOManager manager) {
        this.manager = manager;
    }
    
    
    

    boolean editable;

    public Contacto getContatco() {
        return contacto;
    }

    public void setContatco(Contacto contatco) {
        this.contacto = contatco;
    }

    public boolean isEditable() {
        return editable;
    }

    public void setEditable(boolean editable) {
        this.editable = editable;
        txtNombre.setEditable(editable);
        txtNumero.setEditable(editable);
        txtCorreo.setEditable(editable);
        txtCiudad.setEditable(editable);
        txtTwitter.setEditable(editable);
    }

    public VentanaContacto() {
        initComponents();
        setVisible(true);

        setLocationRelativeTo(null);

        String[] titulo = {"Nombre", "Número", "Correo", "Ciudad", "Twitter"};
        String[][] datos = {};

        modelo = new DefaultTableModel(datos, titulo);

        jTable.setModel(modelo);
    }

    public void limpiar() {
        txtNombre.setText("");
        txtNumero.setText("");
        txtCorreo.setText("");
        txtCiudad.setText("");
        txtTwitter.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel2 = new javax.swing.JPanel();
        barraTareas = new javax.swing.JToolBar();
        botonAgregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        botonEditar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        botonBorrar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        botonGuardar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        botonCancelar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        botonSalir = new javax.swing.JButton();
        PanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        lblAgendaTel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTwitter = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(62, 90, 116));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraTareas.setBackground(new java.awt.Color(108, 108, 108));
        barraTareas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        botonAgregar.setBackground(barraTareas.getBackground());
        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda/Ventanas/add.png"))); // NOI18N
        botonAgregar.setText("Add");
        botonAgregar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        barraTareas.add(botonAgregar);
        barraTareas.add(jSeparator1);

        botonEditar.setBackground(barraTareas.getBackground());
        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda/Ventanas/editar.png"))); // NOI18N
        botonEditar.setText("Editar");
        botonEditar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        barraTareas.add(botonEditar);
        barraTareas.add(jSeparator2);

        botonBorrar.setBackground(barraTareas.getBackground());
        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda/Ventanas/borrar.png"))); // NOI18N
        botonBorrar.setText("Borrar");
        botonBorrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonBorrar.setFocusable(false);
        botonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraTareas.add(botonBorrar);
        barraTareas.add(jSeparator3);

        botonGuardar.setBackground(barraTareas.getBackground());
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda/Ventanas/guardar.png"))); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonGuardar.setFocusable(false);
        botonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraTareas.add(botonGuardar);
        barraTareas.add(jSeparator4);

        botonCancelar.setBackground(barraTareas.getBackground());
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda/Ventanas/cancelar.png"))); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonCancelar.setFocusable(false);
        botonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraTareas.add(botonCancelar);
        barraTareas.add(jSeparator6);
        barraTareas.add(jSeparator7);

        botonSalir.setBackground(botonAgregar.getBackground());
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda/Ventanas/exitPurple.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setBorder(botonBorrar.getBorder());
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        barraTareas.add(botonSalir);

        getContentPane().add(barraTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 50));

        PanelTabla.setLayout(new java.awt.BorderLayout());

        jTable.setBackground(new java.awt.Color(231, 208, 2));
        jTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable.setFont(new java.awt.Font("Hiragino Kaku Gothic StdN", 1, 12)); // NOI18N
        jTable.setForeground(new java.awt.Color(255, 255, 255));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);
        jTable.getAccessibleContext().setAccessibleDescription("gnnvnvnvn");

        PanelTabla.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 610, 160));

        lblAgendaTel.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblAgendaTel.setForeground(new java.awt.Color(88, 143, 0));
        lblAgendaTel.setText("Agenda Telefónica");
        getContentPane().add(lblAgendaTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jPanel3.setBackground(new java.awt.Color(68, 98, 128));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 204), 4, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Datos a guardar/editar/borrar");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo: ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ciudad:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, 20));

        txtCiudad.setBackground(new java.awt.Color(0, 68, 130));
        txtCiudad.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 140, 30));

        txtCorreo.setBackground(new java.awt.Color(0, 68, 130));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 430, 30));

        txtNombre.setBackground(new java.awt.Color(0, 68, 130));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 170, 30));

        txtNumero.setBackground(new java.awt.Color(0, 68, 130));
        txtNumero.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 150, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Número:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, 30));

        txtTwitter.setBackground(new java.awt.Color(0, 68, 130));
        txtTwitter.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtTwitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 210, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Twitter: ");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 570, 200));

        telefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda/images/telefono rojo vector.png"))); // NOI18N
        telefono.setText("hjn");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, telefono, org.jdesktop.beansbinding.ELProperty.create("${background}"), telefono, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 460, 380));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda/images/azul grisáceo.jpg"))); // NOI18N
        getContentPane().add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    public void cargarDatos() {

        if (contacto != null) {
            txtNombre.setText(contacto.getNombre());
            txtNumero.setText(contacto.getNumero());
            txtCorreo.setText(contacto.getCorreo());
            txtCiudad.setText(contacto.getCiudad());
            txtTwitter.setText(contacto.getTwitter());
        } else {
            txtNombre.setText("");
            txtNumero.setText("");
            txtCorreo.setText("");
            txtCiudad.setText("");
            txtTwitter.setText("");
        }
    }

    public void GuardarContacto() {
        if (contacto == null) {
            contacto = new Contacto();
        }
        contacto.setNombre(txtNombre.getText());
        contacto.setNumero(txtNumero.getText());
        contacto.setCorreo(txtCorreo.getText());
        contacto.setCiudad(txtCiudad.getText());
        contacto.setTwitter(txtTwitter.getText());
    }

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        contacto.setNombre(txtNombre.getText());
        contacto.setNumero(txtNumero.getText());
        contacto.setCorreo(txtCorreo.getText());
        contacto.setCiudad(txtCiudad.getText());
        contacto.setTwitter(txtTwitter.getText());

        Object[] datos = {contacto.getNombre(), contacto.getNumero(),
            contacto.getCorreo(), contacto.getCiudad(),
            contacto.getTwitter()};
        modelo.addRow(datos);
        limpiar();
    }//GEN-LAST:event_botonAgregarActionPerformed

    public static void main(String[] args) throws SQLException {
        DAOManager manager = new MySQLDaoManager("localhost", "root", "root", "contactos");
        
        java.awt.EventQueue.invokeLater(() -> {
            //gracias al constructor de arriba le puedo pasar el manager y activar la conexión de un tiro
            new VentanaContacto(manager).setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTabla;
    private javax.swing.JToolBar barraTareas;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel fondo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel lblAgendaTel;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTwitter;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
